const buttonDefs = [
    
    {
        id: 0,
        label: "M+" ,
        function: "memory",
        value: "mPlus",
        color: "orange",
        working: true},
    {
        id : 1,
        label : "M-",
        function : "memory",
        value: "mSub",
        color: "orange",
        working: true},
    {
        id : 2,
        label : "MR",
        function : "memory",
        value: "mRecal",
        color: "orange",
        working: true},
    {
        id : 3,
        label : "MC",
        function : "memory",
        value: "mClear",
        color: "orange",
        working: true},
    {
        id : 4,
        label : "His",
        function : "insert",
        value : "",
        color: "black",
        working: false},
    {
        id: 10,
        label: "π" ,
        function: "insert",
        value : "π",
        color: "black",
        working: true},
    {
        id : 11,
        label : "log",
        function : "insert",
        value : "log(",
        color: "black",
        working: true},
    {
        id : 12,
        label : "%",
        function : "insert",
        value : "%",
        color: "black",
        working: true},
    {
        id : 13,
        label : "√",
        function : "insert",
        value : "sqrt(",
        color: "black",
        working: true},
    {
        id : 14,
        label : <>𝑥<sup>2</sup></>,
        function : "insert",
        value : <sup>2</sup>,
        color: "black",
        working: true},
    {
        id: 15,
        label: "(",
        function: "insert",
        value : "(",
        color: "black",
        working: true},
    {
        id : 16,
        label : ")",
        function : "insert",
        value : ")",
        color: "black",
        working: true},
    {
        id : 17,
        label : "sin",
        function : "insert",
        value : "sin(",
        color: "black",
        working: true},
    {
        id : 18,
        label : "cos",
        function : "insert",
        value : "cos(",
        color: "black",
        working: true},
    {
        id : 19,
        label : "tan",
        function : "insert",
        value : "tan(",
        color: "black",
        working: true},
    {
        id: 20,
        label: "7",
        function: "insert",
        value : "7",
        color: "white",
        working: true},
    {
        id : 21,
        label : "8",
        function : "insert",
        value : "8",
        color: "white",
        working: true},
    {
        id : 22,
        label : "9",
        function : "insert",
        value : "9",
        color: "white",
        working: true},
    {
        id : 23,
        label : "DEL",
        function : "process",
        value : "back",
        color: "orange",
        working: true},
    {
        id : 24,
        label : "AC",
        function : "process",
        value : "clear",
        color : "orange",
        working: true},
    {
        id: 25,
        label: "4",
        function: "insert",
        value : "4",
        color: "white",
        working: true},
    {
        id : 26,
        label : "5",
        function : "insert",
        value : "5",
        color: "white",
        working: true},
    {
        id : 27,
        label : "6",
        function : "insert",
        value : "6",
        color: "white",
        working: true},
    {
        id : 28,
        label : "×",
        function : "operator",
        value : "*",
        color: "white",
        working: true},
    {
        id : 29,
        label : "÷",
        function : "operator",
        value : "/",
        color: "white",
        working: true},
    {
        id: 30,
        label: "1",
        function: "insert",
        value : "1",
        color: "white",
        working: true},
    {
        id : 31,
        label : "2",
        function : "insert",
        value : "2",
        color: "white",
        working: true},
    {
        id : 32,
        label : "3",
        function : "insert",
        value : "3",
        color: "white",
        working: true},
    {
        id : 33,
        label : "+",
        function : "operator",
        value : "+",
        color: "white",
        working: true},
    {
        id : 34,
        label : "-",
        function : "operator",
        value : "-",
        color: "white",
        working: true},
    {
        id: 35,
        label: "0" ,
        function: "insert",
        value : "0",
        color: "white",
        working: true},
    {
        id : 36,
        label : ".",
        function : "insert",
        value : ".",
        color: "white",
        working: true},
    {
        id : 37,
        label: <>x10<sup>𝑥</sup></>,
        function : "insert",
        value : <sub>x10</sub>,
        color: "white",
        working: true},
    {
        id : 38,
        label : "Ans",
        function : "calculate",
        value : "ans",
        color: "white",
        working: true},
    {
        id : 39,
        label : "=",
        function : "calculate",
        value : "equals",
        color: "white",
        working: true}
    
]

export default buttonDefs;